### ISSUE TITLE
Fatura maior que o previsto

### ISSUE THREAD

**Issue by fmatheus** [awmpietro/dolar-nubank#1]
Fala, Arthur, obrigado por essa ferramenta muito prática!
Faz tempo que uso, mas ultimamente ela tem errado para menos em mais de 5%.
PS: se precisar entrar em contato em privado eu forneço números mais específicos.

**Comment by awmpietro** [comment]
Bom dia @fmatheus. Obrigado pelo heads up! Vou verificar se o Nubank mudou algo nos valores de spread deles ou o IOF. O dólar que consulto é o oficial fornecido pelo banco central. Sabe me dizer se houve alguma mudança nesse sentido?

**Comment by fmatheus** [comment]
Acabei de abrir um chamado lá, já que a informação no FAQ não mudou.
A ptax de ontem foi 5,34, com 4% de spread ficaria 5,55 ao invés dos 5,59
que cobraram. Quando responderem te aviso.

Segue o que consta na FAQ do Nubank:

"Qual a cotação utilizada para compras em dólar no cartão de crédito?

Utilizamos o dólar PTAX venda do Banco Central + o spread de 4%.

Ao efetuar uma compra em dólar, nós mostramos no seu app o valor total com
a taxa de câmbio da data da autorização da compra, mais o IOF de 6,38%."

Em sáb, 28 de nov de 2020 11:01, Arthur Mastropietro <
notifications@github.com> escreveu:

**Comment by awmpietro** [comment]
@fmatheus tudo bem? Desculpa a demora. O Nubank te posicionou de alguma forma? Os valores dos cálculos aparentemente estão corretos: 4% de spread, 6,38% de IOF. Vale lembrar também que a cotação do dólar PTAX que o Banco Central expõe em API varia durante o dia. Não só varia, como eles só atualizam o valor 3 ou 4 vezes por dia, ou seja, pode acontecer de no momento da compra o valor do PTAX estar desatualizado em alguns minutos ou horas.

**Comment by fmatheus** [comment]
Só consegui uma resposta aleatória da IA do Nubank, que não tinha nada a
ver com o assunto! :(

Mesmo assim, em um teste posterior em horário comercial, a simulação foi
correta, a diferença anterior deve ser relativa a essa desatualização,
talvez agravada por ser final de semana.
