### ISSUE TITLE
A ferramenta parou de funcionar

### ISSUE THREAD

**Issue by n0santos** [awmpietro/dolar-nubank#3]
![Screenshot 2022-10-28 at 10 53 14](https://user-images.githubusercontent.com/20404955/198625368-45cbc281-120e-4797-ba64-9cd5e1c4bfa1.png)

**Comment by awmpietro** [comment]
Olá @n0santos, obrigado por reportar.
O servidor da API do Banco Central que fornece a cotação oficial do dólar, e que eu uso no app pra fazer o calculo, está fora do ar hoje.
Assim que voltar eu lhe comunico.

**Comment by awmpietro** [comment]
Foi erro na API do BC, já voltou ao ar
