### ISSUE TITLE
Revisar taxa de IOF

### ISSUE THREAD

**Issue by garrucho** [awmpietro/dolar-nubank#4]
Este ano começou a [redução do IOF](https://www.cnnbrasil.com.br/business/iof-sera-reduzido-em-operacoes-de-cambio-relativas-a-transferencias-ao-exterior/) e, na verdade não validei, mas imagino que a calculadora não leva isso em conta.

É necessário atualizar para 5,38%, e se viável implementar o valor conforme a data para cosiderar os anos seguintes.

**Comment by awmpietro** [comment]
Obrigado pela informação @garrucho, eu realmente estava por fora. Já atualizei.
